spring:
  application:
    name: admin-service
  boot:
    admin:
      client:
        url: http://192.168.1.9:8084
  zipkin:
    base-url: http://192.168.1.9:9411
server:
  port: 9000
  servlet:
    context-path: /
eureka:
  client:
    service-url:
     # defaultZone: http://192.168.1.9:7003/eureka/
      defaultZone: http://192.168.1.9:7003/eureka/,http://192.168.1.9:7004/eureka/,http://192.168.1.9:7005/eureka/
    register-with-eureka: true
    fetch-registry: true
#  instance:
#    prefer-ip-address: true
#    instance-id: admin-service
