spring:
  application:
    name: admin-service
  boot:
    admin:
      client:
        url: http://localhost:8084
#  zipkin:
#    base-url: http://localhost:9411
server:
  port: 8000
  servlet:
    context-path: /
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7003/eureka/
    register-with-eureka: true
    fetch-registry: true
#  instance:
#    prefer-ip-address: true
#    instance-id: admin-service
