
server:
  port: 7003
eureka:
  instance:
    hostname: 192.168.1.9     # eureka服务端的实力名称
  client:
    fetch-registry: true  # false表示自己就是注册中心。我的职责就是维护服务实例，并不需要去检索服务
    register-with-eureka: true   # false表示自己不需要向注册中心注册自己
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/   # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址(单机版)
      defaultZone: http://192.168.1.9:7003/eureka/,http://192.168.1.9:7004/eureka/,http://192.168.1.9:7005/eureka/
spring:
  boot:
    admin:
      client:
        url: http://192.168.1.9:8084
  zipkin:
    base-url: http://192.168.1.9:9411