spring:
  #  zipkin:
  #    base-url: http://localhost:9411
  application:
    name: yjw-spring-admin
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.9:7003/eureka/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*" #["health","info"]
