spring:
  zipkin:
    base-url: http://192.168.1.9:9411
  application:
    name: yjw-spring-admin
server:
  port: 8084
eureka:
  client:
    service-url:
    #  defaultZone: http://192.168.1.9:7003/eureka/
      defaultZone: http://192.168.1.9:7003/eureka/,http://192.168.1.9:7004/eureka/,http://192.168.1.9:7005/eureka/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'  #["health","info"]
