spring:
  #  zipkin:
  #    base-url: http://localhost:9411
  application:
    name: web-admin-feign
  boot:
    admin:
      client:
        url: http://192.168.1.9:8084
server:
  port: 8004
  servlet:
    context-path: /
eureka:
  instance:
    prefer-ip-address: true
    instance-id: web-admin-feign
  client:
    service-url:
     # defaultZone: http://192.168.1.9:7003/eureka/
     defaultZone: http://192.168.1.9:7003/eureka/,http://192.168.1.9:7004/eureka/,http://192.168.1.9:7005/eureka/
feign:
  hystrix:
    enabled: true
