spring:
  #  zipkin:
  #    base-url: http://localhost:9411
  application:
    name: zuul
  boot:
    admin:
      client:
        url: http://192.168.1.9:8084
server:
  port: 8005
  servlet:
    context-path: /
eureka:
  client:
    service-url:
    #  defaultZone: http://192.168.1.9:7003/eureka/
     defaultZone: http://192.168.1.9:7003/eureka/,http://192.168.1.9:7004/eureka/,http://192.168.1.9:7005/eureka/ 
zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: web-admin-feign
#    api-b:
#      path: /api/b/**
#      serviceId: b